server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # React/Vite frontend
    location / {
        try_files $uri $uri/ /index.html;
    }

    # FastAPI user service
    location /user-api/ {
        proxy_pass http://user-service:8000/;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Spring Boot transaction service
    location /transaction-api/ {
        proxy_pass http://transaction-service:8080/;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # FastAPI activity service
    location /activity-api/ {
        proxy_pass http://activity-service:8001/;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # FinanceAgent API
    location /finance-agent-api/ {
        proxy_pass http://finance-agent:9001/;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = /frontend-health {
        access_log off;
        add_header Content-Type text/plain;
        return 200 "healthy\n";
    }
}
